#!/bin/bash

# ============================================================================
# Dev CLI Help Module
# ============================================================================
# This module contains help and documentation functions

# Function to show main help
show_help() {
    echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║     Aletheia Developer CLI v3.0       ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
    echo ""
    echo "Usage: ./dev [command] [options]"
    echo ""
    echo -e "${GREEN}🚀 Getting Started:${NC}"
    echo "  setup           Initial setup wizard (generate secure .env)"
    echo "  up              Start all services"
    echo "  status          Check what's running"
    echo "  help            Show this help"
    echo ""
    echo -e "${CYAN}📦 Daily Workflow:${NC}"
    echo "  up [service]    Start services (all or specific)"
    echo "  down [service]  Stop services (all or specific)"
    echo "  restart [name]  Restart services"
    echo "  status [mode]   Check status (simple/explain for variants)"
    echo "  logs [name]     View service logs"
    echo "  shell [name]    Access service container"
    echo ""
    echo -e "${CYAN}🔨 Development:${NC}"
    echo "  rebuild [svc]   Rebuild services (add 'hard' for cache clear)"
    echo "  seed-users      Reset demo users for lawyer-chat"
    echo "  verify-frontend Verify lawyer-chat frontend"
    echo "  reload-nginx    Reload nginx without restart"
    echo ""
    echo -e "${CYAN}🔍 Troubleshooting:${NC}"
    echo "  check [type]    System validation (health/docker/env/ports)"
    echo "  find-orphans    Find containers not in compose file"
    echo "  dependencies    Show service dependency tree"
    echo "  services        List all available services"
    echo ""
    echo -e "${CYAN}💾 Data Management:${NC}"
    echo "  db shell        Open PostgreSQL shell"
    echo "  db schema       Show database schema"
    echo "  backup          Backup database and configs"
    echo "  archive         Move old files to .archive/"
    echo ""
    echo -e "${CYAN}⚙️ Configuration:${NC}"
    echo "  env list        List all environment variables"
    echo "  env status      Check environment configuration"
    echo "  env audit       Find missing variables (--fix to add)"
    echo "  env ports       Show port configuration"
    echo "  docs verify     Check documentation accuracy"
    echo ""
    echo -e "${CYAN}🤖 n8n Workflow Automation:${NC}"
    echo "  execute         Execute workflows with parameters"
    echo "  n8n init        Complete setup wizard"
    echo "  n8n test        Test workflows (webhook or by name)"
    echo "  n8n validate    Health check with fixes"
    echo "  n8n workflows   Manage workflows"
    echo "  n8n monitor     Real-time monitoring"
    echo "  n8n help        More n8n commands"
    echo ""
    echo -e "${CYAN}⚖️ Court Document Processing:${NC}"
    echo "  court status    Check court processor service status"
    echo "  court analyze   Analyze judges, courts, and legal patterns"
    echo "  court collect   Collect documents from various sources"
    echo "  court data      Manage data quality and XML-enhanced collection"
    echo "  court search    Search indexed documents (basic & enhanced)"
    echo "  court help      More court commands"
    echo ""
    echo -e "${CYAN}📊 XML-Enhanced Features:${NC}"
    echo "  court data xml-summary              # Show XML parsing coverage"
    echo "  court data xml-extract --field X    # Extract specific metadata"
    echo "  court search enhanced --xml-only    # Search XML documents only"
    echo ""
    echo -e "${RED}⚠️ Destructive Operations:${NC}"
    echo "  purge           Stop all services and DELETE ALL DATA"
    echo ""
    echo -e "${CYAN}Common Workflows:${NC}"
    echo ""
    echo -e "  ${GREEN}First Time Setup:${NC}"
    echo "  ./dev setup               # Generate .env file"
    echo "  ./dev up                  # Start all services"
    echo "  ./dev status              # Verify everything is running"
    echo "  ./dev n8n init            # Setup n8n automation"
    echo ""
    echo -e "  ${GREEN}Daily Development:${NC}"
    echo "  ./dev up                  # Start your dev environment"
    echo "  ./dev logs -f             # Watch logs (Ctrl+C to exit)"
    echo "  ./dev status simple       # Quick health check"
    echo "  ./dev down                # End of day shutdown"
    echo ""
    echo -e "  ${GREEN}Debugging Issues:${NC}"
    echo "  ./dev check               # Full system validation"
    echo "  ./dev logs n8n            # Check specific service logs"
    echo "  ./dev shell n8n           # Access container shell"
    echo "  ./dev restart n8n         # Restart problematic service"
    echo ""
    echo -e "  ${GREEN}Working with n8n:${NC}"
    echo "  ./dev n8n test webhook    # Test Main workflow"
    echo "  ./dev n8n monitor         # Watch workflow executions"
    echo "  ./dev n8n validate        # Check n8n health"
}

# Function to show n8n help
show_n8n_help() {
    echo "Usage: ./dev n8n {setup|workflows|nodes|cli|credentials|executions|env|test|monitor|query} [command]"
    echo ""
    echo "Subcommands:"
    echo "  setup       - Auto-setup n8n owner account and activate workflows"
    echo "  workflows   - Manage workflows (list, import, export, execute, activate/deactivate)"
    echo "  nodes       - Manage custom nodes (list, build, verify)"
    echo "  credentials - Manage credentials (export, import, backup)"
    echo "  executions  - View workflow executions"
    echo "  env         - Manage environment variables"
    echo "  test        - Test n8n functionality (webhooks)"
    echo "  monitor     - Continuous monitoring (logs, webhooks, executions, errors)"
    echo "  query       - Query n8n status and configuration"
    echo "  cli         - Pass commands directly to n8n CLI"
    echo ""
    echo "Examples:"
    echo "  ./dev n8n workflows list             # List all workflows"
    echo "  ./dev n8n env list                   # List container env vars"
    echo "  ./dev n8n monitor executions         # Watch workflow executions"
    echo "  ./dev n8n query status               # Check n8n status"
    echo "  ./dev n8n credentials backup          # Backup all credentials"
}

# Export functions
export -f show_help
export -f show_n8n_help