#!/bin/bash

# ============================================================================
# Dev CLI Help Module
# ============================================================================
# This module contains help and documentation functions

# Function to show main help
show_help() {
    echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║     Aletheia Developer CLI v3.0       ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
    echo ""
    echo "Usage: ./dev [command] [options]"
    echo ""
    echo -e "${CYAN}Core Commands:${NC}"
    echo "  up [service]    Start all services (or specific one)"
    echo "  down [service]  Stop all services (or specific one)"
    echo "  restart [name]  Restart a specific service (or all if no name)"
    echo "  logs [name]     Show logs (all services or specific one)"
    echo "  status          Show detailed status of all services"
    echo "  services        List all available services"
    echo "  shell [name]    Open shell in a container"
    echo ""
    echo -e "${CYAN}Health & Validation:${NC}"
    echo "  health          Run health checks on all services"
    echo "  validate        Validate setup and configuration"
    echo "  ports           Show port usage and availability"
    echo ""
    echo -e "${CYAN}Documentation & Info:${NC}"
    echo "  docs verify     Check documentation accuracy"
    echo "  docs update     Update docs from running system (planned)"
    echo "  db schema       Show database schema"
    echo "  db shell        Open PostgreSQL shell"
    echo "  env check       Verify environment configuration"
    echo "  env list        List all environment variables"
    echo ""
    echo -e "${CYAN}n8n Automation:${NC}"
    echo "  n8n setup       Initialize owner account & activate workflows"
    echo "  n8n workflows   Manage workflows (list, import, export, execute, activate/deactivate)"
    echo "  n8n credentials Manage credentials (export, import, backup)"
    echo "  n8n monitor     Real-time execution monitoring"
    echo "  n8n query       Query execution data and statistics"
    echo "  n8n nodes       Manage custom nodes (list, build, verify)"
    echo "  n8n executions  View workflow execution history"
    echo "  n8n cli         Direct access to n8n CLI commands"
    echo ""
    echo -e "${CYAN}Setup & Maintenance:${NC}"
    echo "  setup           Initial setup wizard (generate secure .env)"
    echo "  doctor          Run comprehensive system diagnostics"
    echo "  backup          Backup database and configurations"
    echo "  rebuild [opts]  Rebuild services with cache control"
    echo "                  Options: [service] --hard --verify"
    echo "  verify-frontend Run frontend verification for lawyer-chat"
    echo "  cleanup         Archive old/backup files to .archive/"
    echo "  clean           Stop services and clean volumes (WARNING: deletes data)"
    echo "  reload-nginx    Reload nginx configuration without restart"
    echo "  seed-users      Initialize/reset lawyer-chat demo users"
    echo ""
    echo -e "${CYAN}Examples:${NC}"
    echo "  ./dev up                  # Start everything"
    echo "  ./dev up n8n             # Start only n8n service"
    echo "  ./dev down lawyer-chat   # Stop only lawyer-chat"
    echo "  ./dev rebuild lawyer-chat # Rebuild lawyer-chat with standard cache clear"
    echo "  ./dev rebuild --hard      # Rebuild all with aggressive cache clearing"
    echo "  ./dev health              # Check if everything is working"
    echo "  ./dev logs n8n           # Show n8n logs"
    echo "  ./dev shell db           # Open PostgreSQL shell"
    echo "  ./dev n8n monitor executions # Real-time execution monitor"
    echo "  ./dev n8n query stats    # View execution statistics"
}

# Function to show n8n help
show_n8n_help() {
    echo "Usage: ./dev n8n {setup|workflows|nodes|cli|credentials|executions|env|test|monitor|query} [command]"
    echo ""
    echo "Subcommands:"
    echo "  setup       - Auto-setup n8n owner account and activate workflows"
    echo "  workflows   - Manage workflows (list, import, export, execute, activate/deactivate)"
    echo "  nodes       - Manage custom nodes (list, build, verify)"
    echo "  credentials - Manage credentials (export, import, backup)"
    echo "  executions  - View workflow executions"
    echo "  env         - Manage environment variables"
    echo "  test        - Test n8n functionality (webhooks)"
    echo "  monitor     - Continuous monitoring (logs, webhooks, executions, errors)"
    echo "  query       - Query n8n status and configuration"
    echo "  cli         - Pass commands directly to n8n CLI"
    echo ""
    echo "Examples:"
    echo "  ./dev n8n workflows list             # List all workflows"
    echo "  ./dev n8n env list                   # List container env vars"
    echo "  ./dev n8n monitor executions         # Watch workflow executions"
    echo "  ./dev n8n query status               # Check n8n status"
    echo "  ./dev n8n credentials backup          # Backup all credentials"
}

# Export functions
export -f show_help
export -f show_n8n_help